tap "homebrew/bundle"
tap "sikalabs/tap"

# Formulae (top-level leaves)
brew "argocd"
brew "awscli"
brew "fzf"
brew "gh"
brew "helm"
brew "k9s"
brew "kube-ps1"
brew "kubectx"
brew "kustomize"
brew "mas"
brew "midnight-commander"
brew "neovim"
brew "node"
brew "openjdk"
brew "openshift-cli"
brew "postgresql@18"
brew "sikalabs/tap/slu"
brew "telnet"
brew "terraform"
brew "tmux"
brew "wakeonlan"
brew "watch"
brew "yq"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Casks
cask "1password"
cask "affinity"
cask "aldente"
cask "appcleaner"
cask "balenaetcher"
cask "battle-net"
cask "bitwarden"
cask "claude"
cask "curseforge"
cask "cyberduck"
cask "dictionaries"
cask "discord"
cask "docker-desktop"
cask "fleet"
cask "chatgpt"
cask "iterm2"
cask "microsoft-edge"
cask "microsoft-onenote"
cask "onedrive"
cask "proton-drive"
cask "proton-mail"
cask "protonvpn"
cask "raspberry-pi-imager"
cask "sdformatter"
cask "steam"
cask "tailscale-app"
cask "telegram"
cask "utm"
cask "visual-studio-code"
cask "vlc"
cask "warp"

# Mac App Store apps
mas " 1Password for Safari ", id: 1569813296
mas "  Amphetamine          ", id: 937984704
mas " Clamshell            ", id: 6477896729
mas "  Keynote              ", id: 409183694
mas "  LanScan              ", id: 472226235
mas " Mic Drop             ", id: 1489816366
mas "  Microsoft Excel      ", id: 462058435
mas "  Microsoft Outlook    ", id: 985367838
mas "  Microsoft PowerPoint ", id: 462062816
mas "  Microsoft Word       ", id: 462054704
mas "  Numbers              ", id: 409203825
mas "  Pages                ", id: 409201541
mas " Pure Paste           ", id: 1611378436
mas " Windows App          ", id: 1295203466
